# DONT EDIT. This file is synced from https://github.com/cloudquery/.github
before:
  hooks:
    - go mod download
builds:
  - flags:
      - -buildmode=exe
    env:
      - GOGC=off
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./main.go
    ldflags:
      - -s -w -X github.com/ShuBo6/cloudquery/pkg/core.Version={{.Version}} -X github.com/ShuBo6/cloudquery/cmd.Commit={{.Commit}} -X github.com/ShuBo6/cloudquery/cmd.Date={{.Date}} -X github.com/ShuBo6/cloudquery/cmd.APIKey=28iMwucm5GXsoevNGSfDl1LC6zV
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
archives:
  -
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: binary
  -
    id: homebrew
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: zip
dockers:
  -
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "ghcr.io/cloudquery/cloudquery:latest"
      - "ghcr.io/cloudquery/cloudquery:{{.Version}}"
      - "ghcr.io/cloudquery/cloudquery:{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - "--label=org.opencontainers.image.source=https://github.com/ShuBo6/cloudquery"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      
release:
  prerelease: auto